Fixed sent card issue

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,26 +1,31 @@
-name: Build Nu Age EXE (Manual Env Mode)
+name: Build Nu Age APK (Manual Env Mode)
 
 on:
   workflow_dispatch:
 
 jobs:
   build:
-    name: Build EXE
-    runs-on: windows-latest
-
-    env:
-      PYTHONUTF8: "1"
-      PYTHONIOENCODING: "utf-8"
+    name: Build APK
+    runs-on: ubuntu-latest
 
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
+      - name: Setup Java (Required for Android)
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'zulu'
+          java-version: '17'
+
       - name: Setup Flutter
         uses: subosito/flutter-action@v2
         with:
           channel: 'stable'
-
+      - name: Accept Android SDK Licenses
+        run: |
+          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
+          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update || true
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
@@ -31,20 +36,20 @@ jobs:
           python -m pip install --upgrade pip
           pip install flet-cli==0.84.0 flet==0.84.0 flet-video==0.84.0 flet-charts==0.84.0 httpx==0.28.1 requests==2.33.1
 
-      - name: Compile the EXE
+      - name: Compile the APK
         run: |
-          flet build windows --product "Nu Age" --verbose
-          if ($LASTEXITCODE -ne 0) {
-            Write-Error "CRITICAL ERROR: Flet compiler crashed! Check verbose logs for Dart/Python errors."
+          if ! flet build apk --product "Nu Age" --verbose; then
+            echo "::error::CRITICAL ERROR: Flet compiler crashed! Check verbose logs for Dart/Python errors."
             exit 1
-          }
+          fi
 
-      - name: Rename the EXE file
+      - name: Rename the APK file
         run: |
-          Get-ChildItem -Path build/windows -Filter *.exe | Rename-Item -NewName "Nu Age.exe"
+          cd build/apk
+          mv *.apk "Nu Age.apk"
 
-      - name: Upload Full App Folder
+      - name: Upload APK
         uses: actions/upload-artifact@v4
         with:
           name: Nu Age App
-          path: build/windows/
+          path: build/apk/Nu Age.apk
